output:
  format: "json" # Maybe add option for pickle?
  dir: "./output/"
  file: "output.json"
warmup: True
warmup_options:
  requests: 11
  timeout_sec: 20
storage: # TODO
  type: local
dataset:
  file: "datasets/openorca_large_subset_011.jsonl"
  max_queries: 1000
  min_input_tokens: 0
  max_input_tokens: 1024
  max_output_tokens: 256
  max_sequence_tokens: 1024
load_options:
  type: constant #Future options: loadgen, stair-step
  concurrency: 2
  duration: 20 # In seconds. Maybe in future support "100s" "10m", etc...
plugin: "tgis_grpc_plugin"
plugin_options:
  #interface: "grpc" # Some plugins like caikit-nlp-client should support grpc/http
  use_tls: False # Use True if querying an SSL grpc endpoint over https
  streaming: True
  model_name: "flan-t5-small"
  host: "route.to.host"
  port: 8033
extra_metadata:
  replicas: 1
metadata_extensions_enabled: True
metadata_extensions_options:
# https://prometheus.demo.do.prometheus.io/graph?g0.expr=container_network_transmit_bytes_total&g0.tab=0&g0.display_mode=lines&g0.show_exemplars=1&g0.range_input=30m&g0.end_input=2024-06-26%2017%3A32%3A36&g0.moment_input=2024-06-26%2017%3A32%3A36
  - prometheus:
    - base_url: 'https://prometheus.demo.do.prometheus.io'
      user: 'myuser'
      password: 'mypassword'
      metric: 'container_cpu_usage_seconds_total'
      expected_labels:
        env: 'demo'
        id: '/'
        instance: 'demo.do.prometheus.io:8080'
        job: 'cadvisor'
        cpu: 'total'
    - base_url: 'https://prometheus.demo.do.prometheus.io'
      user: 'myuser'
      password: 'mypassword'
      metric: 'container_memory_usage_bytes'
      expected_labels:
        env: 'demo'
        id: '/'
        instance: 'demo.do.prometheus.io:8080'
        job: 'cadvisor'
  - prometheus2:
    - base_url: 'https://prometheus.demo.do.prometheus.io'
      user: 'myuser'
      password: 'mypassword'
      metric: 'container_network_transmit_bytes_total'
      expected_labels:
        env: 'demo'
        id: '/'
        instance: 'demo.do.prometheus.io:8080'
        job: 'cadvisor'
        interface: eth0
